name: 'Publish Allure report to NeoFS'
description: 'This action allows you to publish Allure reports to NeoFS.'
author: 'Neo SPCC'
branding:
  icon: 'server'
  color: 'green'
inputs:
  NEOFS_WALLET:
    description: N3 wallet for NeoFS network access
    required: true
  NEOFS_WALLET_PASSWORD:
    description: N3 wallet password
    required: true
  NEOFS_NETWORK_DOMAIN:
    description: Rpc endpoint domain address
    required: false
    default: 'st1.storage.fs.neo.org'
  NEOFS_HTTP_GATE:
    description: HTTP Gateway domain address
    required: false
    default: 'http.fs.neo.org'
  STORE_OBJECTS_CID:
    description: Container ID for your data
    required: true
  PR_LIFETIME:
    description: Expiration period for PRs in epochs
    required: false
    default: 0
  MASTER_LIFETIME:
    description: Expiration period for master branch in epochs
    required: false
    default: 0
  MANUAL_RUN_LIFETIME:
    description: Expiration period for manual runs in epochs
    required: false
    default: 0
  OTHER_LIFETIME:
    description: Expiration period for other events in epochs
    required: false
    default: 0
  ALLURE_RESULTS_DIR:
    description: Path to Allure result
    required: true
  ALLURE_GENERATED_DIR:
    description: Path to store Allure generated report
    required: false
    default: './tests/neofs-test-allure-generated-report'

outputs:
  REPORT_NEOFS_URL:
    description: Container URL
    value: ${{ steps.gh_push_to_neofs.outputs.OUTPUT_CONTAINER_URL }}${{ github.run_number }}-${{ steps.date.outputs.timestamp }}/
  COMBINED_REPORT_DIR:
    description: Path to the directory with the combined Allure report and zip attachments
    value: ${{ steps.set_report_dir.outputs.REPORT_DIR }}

env:
  ALLURE_RESULTS_DIR: ${GITHUB_WORKSPACE}/test_delete_metadata

jobs:
  a_r:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'

      - uses: actions/checkout@v4
      - name: Publish Allure report to Morph object storage
        id: publish_to_morph_object_storage
        uses: morphbits-io/gh-push-to-morph@main
        with:
          MORPH_USER_NAME: ${{ secrets.MORPH_USER_NAME }}
          MORPH_USER_PASSWORD: ${{ secrets.MORPH_USER_PASSWORD }}
          ALLURE_REPORT_BUCKET_NAME: ${{ vars.ALLURE_REPORT_BUCKET_NAME }}
          ALLURE_RESULTS_DIR: ${{ env.ALLURE_RESULTS_DIR }}

      - name: Post a link to the Allure report stored in the Morph object repository
        id: post_report_link
        timeout-minutes: 60
        if: always() && steps.publish_to_morph_object_storage.outcome == 'success'
        env:
          ALLURE_REPORT_URL: ${{ steps.publish_to_morph_object_storage.outputs.ALLURE_REPORT_URL }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'A link to the Allure report stored in the Morph object repository'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: ${{ env.ALLURE_REPORT_URL }}
