name: Run automated tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - support/**
    types: [opened, synchronize]
    paths-ignore:
      - '**/*.md'
  release:
    types:
      - published
  workflow_dispatch:

permissions: write-all


jobs:
  a_r:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'

      - name: Run tests and store allure result
        env:
          ALLURE_RESULTS_DIR: ./test_delete_metadata
        run: |
          ls -lah .
          echo "ALLURE_RESULTS_DIR"
          ls -lah "$ALLURE_RESULTS_DIR"

      - name: Publish Allure report to Morph object storage
        id: publish_to_morph_object_storage
        uses: morphbits-io/gh-push-to-morph@main
        with:
          MORPH_USER_NAME: ${{ secrets.MORPH_USER_NAME }}
          MORPH_USER_PASSWORD: ${{ secrets.MORPH_USER_PASSWORD }}
          ALLURE_REPORT_BUCKET_NAME: ${{ vars.ALLURE_REPORT_BUCKET_NAME }}
          ALLURE_RESULTS_DIR: ./test_delete_metadata

      - name: Post a link to the Allure report stored in the Morph object repository
        id: post_report_link
        timeout-minutes: 60
        if: always() && steps.publish_to_morph_object_storage.outcome == 'success'
        env:
          ALLURE_REPORT_URL: ${{ steps.publish_to_morph_object_storage.outputs.ALLURE_REPORT_URL }}
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'A link to the Allure report stored in the Morph object repository'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: ${{ env.ALLURE_REPORT_URL }}
